<?php
use Illuminate\Support\Facades\Facade;
return [
    'name' => env('APP_NAME', 'Akaunting'),
    'installed' => (bool) env('APP_INSTALLED', false),
    'schedule_time' => env('APP_SCHEDULE_TIME', '09:00'),
    'eager_load' => (bool) env('APP_EAGER_LOAD', true),
    'throttles' => [
        'api' => env('APP_THROTTLES_API', '60'),
        'import' => env('APP_THROTTLES_IMPORT', '1'),
        'email' => [
            'minute' => env('APP_THROTTLES_EMAIL_MINUTE', '5'),
            'month' => env('APP_THROTTLES_EMAIL_MONTH', '500'),
        ],
    ],
    'env' => env('APP_ENV', 'local'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', ''),
    'asset_url' => env('ASSET_URL'),
    'timezone' => env('APP_TIMEZONE', 'UTC'),
    'locale' => env('APP_LOCALE', 'en-GB'),
    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'en-GB'),
    'faker_locale' => env('APP_FAKER_LOCALE', 'en_GB'),
    'key' => env('APP_KEY', 'JustAKeyForAkauntingInstallation'),
    'cipher' => env('APP_CIPHER', 'AES-256-CBC'),
    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,
        Laravel\Tinker\TinkerServiceProvider::class,
        App\Providers\App::class,
        App\Providers\Auth::class,
        App\Providers\Binding::class,
        App\Providers\Blade::class,
        App\Providers\Event::class,
        App\Providers\Macro::class,
        App\Providers\Observer::class,
        App\Providers\Queue::class,
        App\Providers\Route::class,
        App\Providers\Validation::class,
        App\Providers\ViewComposer::class,
    ],
    'aliases' => Facade::defaultAliases()->merge([
        'Date' => App\Utilities\Date::class,
    ])->toArray(),
];
