<?php
return [
    'api_key' => env('BUGSNAG_API_KEY', ''),
    'app_type' => env('BUGSNAG_APP_TYPE'),
    'app_version' => env('BUGSNAG_APP_VERSION'),
    'batch_sending' => env('BUGSNAG_BATCH_SENDING', true),
    'endpoint' => env('BUGSNAG_ENDPOINT'),
    'filters' => empty(env('BUGSNAG_FILTERS')) ? null : explode(',', str_replace(' ', '', env('BUGSNAG_FILTERS'))),
    'hostname' => env('BUGSNAG_HOSTNAME', env('APP_URL')),
    'proxy' => array_filter([
        'http' => env('HTTP_PROXY'),
        'https' => env('HTTPS_PROXY'),
        'no' => empty(env('NO_PROXY')) ? null : explode(',', str_replace(' ', '', env('NO_PROXY'))),
    ]),
    'project_root' => env('BUGSNAG_PROJECT_ROOT'),
    'project_root_regex' => env('BUGSNAG_PROJECT_ROOT_REGEX'),
    'strip_path' => env('BUGSNAG_STRIP_PATH'),
    'strip_path_regex' => env('BUGSNAG_STRIP_PATH_REGEX'),
    'query' => env('BUGSNAG_QUERY', true),
    'bindings' => env('BUGSNAG_QUERY_BINDINGS', false),
    'release_stage' => env('BUGSNAG_RELEASE_STAGE'),
    'notify_release_stages' => empty(env('BUGSNAG_NOTIFY_RELEASE_STAGES')) ? null : explode(',', str_replace(' ', '', env('BUGSNAG_NOTIFY_RELEASE_STAGES'))),
    'send_code' => env('BUGSNAG_SEND_CODE', true),
    'callbacks' => env('BUGSNAG_CALLBACKS', true),
    'user' => env('BUGSNAG_USER', true),
    'logger_notify_level' => env('BUGSNAG_LOGGER_LEVEL'),
    'auto_capture_sessions' => env('BUGSNAG_CAPTURE_SESSIONS', false),
    'session_endpoint' => env('BUGSNAG_SESSION_ENDPOINT'),
    'build_endpoint' => env('BUGSNAG_BUILD_ENDPOINT'),
    'discard_classes' => empty(env('BUGSNAG_DISCARD_CLASSES')) ? null : explode(',', env('BUGSNAG_DISCARD_CLASSES')),
    'redacted_keys' => empty(env('BUGSNAG_REDACTED_KEYS')) ? null : explode(',', env('BUGSNAG_REDACTED_KEYS')),
    'feature_flags' => [],
    'before_send' => [env('BUGSNAG_BEFORE_SEND_CLASS', 'App\\Exceptions\\Trackers\\Bugsnag'), 'beforeSend'],
];
