<?php
return [
    'exports' => [
        'chunk_size' => env('EXCEL_EXPORTS_CHUNK_SIZE', 100),
        'pre_calculate_formulas' => env('EXCEL_EXPORTS_PRE_CALCULATE_FORMULAS', false),
        'strict_null_comparison' => env('EXCEL_EXPORTS_STRING_NULL_COMPARISON', false),
        'csv' => [
            'delimiter'              => ',',
            'enclosure'              => '"',
            'line_ending'            => PHP_EOL,
            'use_bom'                => false,
            'include_separator_line' => false,
            'excel_compatibility'    => false,
        ],
        'properties' => [
            'creator'        => 'Akaunting',
            'lastModifiedBy' => '',
            'title'          => '',
            'description'    => '',
            'subject'        => '',
            'keywords'       => '',
            'category'       => '',
            'manager'        => '',
            'company'        => '',
        ],
        'row_count'     => env('EXCEL_EXPORTS_ROW_COUNT', 250),
        'column_count'  => env('EXCEL_EXPORTS_COLUMN_COUNT', 25),
    ],
    'imports' => [
        'chunk_size' => env('EXCEL_IMPORTS_CHUNK_SIZE', 100),
        'row_limit' => env('EXCEL_IMPORTS_ROW_LIMIT', 1000),
        'extensions' => env('EXCEL_IMPORTS_EXTENSIONS', 'xls,xlsx'),
        'read_only' => env('EXCEL_IMPORTS_READ_ONLY', true),
        'ignore_empty' => env('EXCEL_IMPORTS_IGNORE_EMPTY', true),
        'heading_row' => [
            'formatter' => 'slug',
        ],
        'csv' => [
            'delimiter'        => ',',
            'enclosure'        => '"',
            'escape_character' => '\\',
            'contiguous'       => false,
            'input_encoding'   => 'UTF-8',
        ],
        'properties'  => [
            'creator'        => 'Akaunting',
            'lastModifiedBy' => '',
            'title'          => '',
            'description'    => '',
            'subject'        => '',
            'keywords'       => '',
            'category'       => '',
            'manager'        => '',
            'company'        => '',
        ],
    ],
    'extension_detector' => [
        'xlsx'     => 'Xlsx',
        'xlsm'     => 'Xlsx',
        'xltx'     => 'Xlsx',
        'xltm'     => 'Xlsx',
        'xls'      => 'Xls',
        'xlt'      => 'Xls',
        'ods'      => 'Ods',
        'ots'      => 'Ods',
        'slk'      => 'Slk',
        'xml'      => 'Xml',
        'gnumeric' => 'Gnumeric',
        'htm'      => 'Html',
        'html'     => 'Html',
        'csv'      => 'Csv',
        'tsv'      => 'Csv',
        'pdf' => 'Dompdf',
    ],
    'value_binder' => [
        'default' => 'Maatwebsite\Excel\DefaultValueBinder',
    ],
    'cache' => [
        'driver'     => env('EXCEL_CACHE_DRIVER', 'memory'),
        'batch'     => [
            'memory_limit' => env('EXCEL_CACHE_BATCH_MEMORY_LIMIT', 60000),
        ],
        'illuminate' => [
            'store' => null,
        ],
    ],
    'transactions' => [
        'handler' => env('EXCEL_TRANSACTIONS_HANDLER', 'db'),
    ],
    'temporary_files' => [
        'local_path' => storage_path('app/temp'),
        'remote_disk'       => env('EXCEL_TEMPORARY_FILES_REMOTE_DISK'),
        'remote_prefix'     => env('EXCEL_TEMPORARY_FILES_REMOTE_PREFIX'),
        'force_resync_remote' => env('EXCEL_TEMPORARY_FILES_FORCE_RESYNC_REMOTE'),
    ],
];
