<?php
return [
    'namespace' => 'Modules',
    'stubs' => [
        'enabled' => true,
        'path' => base_path('app/Console/Stubs/Modules'),
        'files' => [
            'listeners/install' => 'Listeners/FinishInstallation.php',
            'providers/event' => 'Providers/Event.php',
            'routes/admin' => 'Routes/admin.php',
            'routes/portal' => 'Routes/portal.php',
            'lang/general' => 'Resources/lang/en-GB/general.php',
            'views/index' => 'Resources/views/index.blade.php',
            'composer' => 'composer.json',
            'assets/js/app' => 'Resources/assets/js/app.js',
            'assets/sass/app' => 'Resources/assets/sass/app.scss',
            'webpack' => 'webpack.mix.js',
            'package' => 'package.json',
        ],
        'replacements' => [
            'listeners/install' => ['ALIAS', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'providers/event' => ['ALIAS', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'routes/admin' => ['ALIAS', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'routes/portal' => ['ALIAS', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'webpack' => ['ALIAS'],
            'json' => ['ALIAS', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'lang/general' => ['ALIAS', 'STUDLY_NAME'],
            'views/index' => ['ALIAS', 'STUDLY_NAME'],
            'composer' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'VENDOR',
                'AUTHOR_NAME',
                'AUTHOR_EMAIL',
                'MODULE_NAMESPACE',
            ],
        ],
        'gitkeep' => false,
    ],
    'paths' => [
        'modules' => base_path(env('MODULE_PATHS_MODULES', 'modules')),
        'assets' => public_path(env('MODULE_PATHS_ASSETS', 'modules')),
        'migration' => base_path(env('MODULE_PATHS_MIGRATION', 'database/migrations')),
        'generator' => [
            'config' => ['path' => 'Config', 'generate' => false],
            'command' => ['path' => 'Console', 'generate' => true],
            'migration' => ['path' => 'Database/Migrations', 'generate' => true],
            'seeder' => ['path' => 'Database/Seeds', 'generate' => true],
            'factory' => ['path' => 'Database/Factories', 'generate' => true],
            'model' => ['path' => 'Models', 'generate' => true],
            'controller' => ['path' => 'Http/Controllers', 'generate' => true],
            'middleware' => ['path' => 'Http/Middleware', 'generate' => false],
            'request' => ['path' => 'Http/Requests', 'generate' => true],
            'provider' => ['path' => 'Providers', 'generate' => true],
            'resource' => ['path' => 'Http/Resources', 'generate' => false],
            'asset' => ['path' => 'Resources/assets', 'generate' => false],
            'lang' => ['path' => 'Resources/lang/en-GB', 'generate' => true],
            'view' => ['path' => 'Resources/views', 'generate' => true],
            'test' => ['path' => 'Tests', 'generate' => false],
            'repository' => ['path' => 'Repositories', 'generate' => false],
            'event' => ['path' => 'Events', 'generate' => false],
            'listener' => ['path' => 'Listeners', 'generate' => true],
            'policy' => ['path' => 'Policies', 'generate' => false],
            'rule' => ['path' => 'Rules', 'generate' => false],
            'job' => ['path' => 'Jobs', 'generate' => true],
            'email' => ['path' => 'Emails', 'generate' => false],
            'notification' => ['path' => 'Notifications', 'generate' => false],
            'route' => ['path' => 'Routes', 'generate' => true],
            'component' => ['path' => 'View/Components', 'generate' => false],
            'cast' => ['path' => 'Casts', 'generate' => false],
        ],
    ],
    'scan' => [
        'enabled' => false,
        'paths' => [
            base_path('vendor
    'composer' => [
        'vendor' => 'akaunting',
        'author' => [
            'name' => 'Akaunting',
            'email' => 'info@akaunting.com',
        ],
    ],
    'cache' => [
        'enabled' => false,
        'key' => 'module',
        'lifetime' => 60,
    ],
    'autoload' => [
        'translations'  => true,
        'files'         => 'register',
        'composer'      => 'register',
    ],
    'activator' => env('MODULE_ACTIVATOR', \App\Utilities\ModuleActivator::class),
];
