<?php declare(strict_types=1);
return [
    'paths' => [
        base_path('app'),
        base_path('database'),
        base_path('modules'),
        base_path('tests'),
    ],
    'exclude' => [
    ],
    'custom_component_classifier' => [
        'App\Classifiers\BulkAction',
        'App\Classifiers\Event',
        'App\Classifiers\Export',
        'App\Classifiers\Import',
        'App\Classifiers\Job',
        'App\Classifiers\Observer',
        'App\Classifiers\Report',
        'App\Classifiers\Scope',
        'App\Classifiers\Widget',
    ],
    'rejection_strategy' => 'Wnx\LaravelStats\RejectionStrategies\RejectVendorClasses',
    'ignored_namespaces' => [
        'Akaunting',
        'Barryvdh',
        'Collective',
        'Composer',
        'ConsoleTVs',
        'Dingo',
        'Doctrine',
        'Dompdf',
        'Facade',
        'Fruitcake',
        'GeneaLabs',
        'GrahamCampbell',
        'Hoa',
        'Http',
        'Illuminate',
        'Intervention',
        'Jenssegers',
        'Kyslik',
        'Laracasts',
        'Laratrust',
        'Lorisleiva',
        'Maatwebsite',
        'Monooso',
        'NunoMaduro',
        'Omnipay',
        'Plank',
        'Psr',
        'Riverskies',
        'SebastianBergmann',
        'Symfony',
        'Wnx\LaravelStats',
    ],
];
