<?php
use Illuminate\Support\Facades\Route;
Route::group(['as' => 'api.', 'middleware' => ['auth:sanctum'], 'namespace' => 'Auth'], function () {
    Route::post('logout', 'Login@logout')->name('logout');
    Route::get('profile', 'Login@profile')->name('profile');
});
Route::group(['as' => 'api.'], function () {
    Route::get('ping', 'Common\Ping@pong')->name('ping');
    Route::get('users/{user}/enable', 'Auth\Users@enable')->name('users.enable');
    Route::get('users/{user}/disable', 'Auth\Users@disable')->name('users.disable');
    Route::apiResource('users', 'Auth\Users');
    Route::get('companies/{company}/owner', 'Common\Companies@canAccess')->name('companies.owner');
    Route::get('companies/{company}/enable', 'Common\Companies@enable')->name('companies.enable');
    Route::get('companies/{company}/disable', 'Common\Companies@disable')->name('companies.disable');
    Route::apiResource('companies', 'Common\Companies', ['middleware' => ['dropzone']]);
    Route::get('dashboards/{dashboard}/enable', 'Common\Dashboards@enable')->name('dashboards.enable');
    Route::get('dashboards/{dashboard}/disable', 'Common\Dashboards@disable')->name('dashboards.disable');
    Route::apiResource('dashboards', 'Common\Dashboards');
    Route::get('items/{item}/enable', 'Common\Items@enable')->name('items.enable');
    Route::get('items/{item}/disable', 'Common\Items@disable')->name('items.disable');
    Route::apiResource('items', 'Common\Items', ['middleware' => ['dropzone']]);
    Route::get('contacts/{contact}/enable', 'Common\Contacts@enable')->name('contacts.enable');
    Route::get('contacts/{contact}/disable', 'Common\Contacts@disable')->name('contacts.disable');
    Route::apiResource('contacts', 'Common\Contacts');
    Route::get('documents/{document}/received', 'Document\Documents@received')->name('documents.received');
    Route::apiResource('documents', 'Document\Documents', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::apiResource('documents.transactions', 'Document\DocumentTransactions', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::get('accounts/{account}/enable', 'Banking\Accounts@enable')->name('accounts.enable');
    Route::get('accounts/{account}/disable', 'Banking\Accounts@disable')->name('accounts.disable');
    Route::apiResource('accounts', 'Banking\Accounts', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::apiResource('reconciliations', 'Banking\Reconciliations', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::apiResource('transactions', 'Banking\Transactions', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::apiResource('transfers', 'Banking\Transfers', ['middleware' => ['date.format', 'money', 'dropzone']]);
    Route::apiResource('reports', 'Common\Reports');
    Route::get('categories/{category}/enable', 'Settings\Categories@enable')->name('categories.enable');
    Route::get('categories/{category}/disable', 'Settings\Categories@disable')->name('categories.disable');
    Route::apiResource('categories', 'Settings\Categories');
    Route::get('currencies/{currency}/enable', 'Settings\Currencies@enable')->name('currencies.enable');
    Route::get('currencies/{currency}/disable', 'Settings\Currencies@disable')->name('currencies.disable');
    Route::apiResource('currencies', 'Settings\Currencies');
    Route::get('taxes/{tax}/enable', 'Settings\Taxes@enable')->name('taxes.enable');
    Route::get('taxes/{tax}/disable', 'Settings\Taxes@disable')->name('taxes.disable');
    Route::apiResource('taxes', 'Settings\Taxes');
    Route::apiResource('settings', 'Settings\Settings');
    Route::get('translations/{locale}/all', 'Common\Translations@all')->name('translations.all');
    Route::get('translations/{locale}/{file}', 'Common\Translations@file')->name('translations.file');
});
