import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:get_it/get_it.dart';
import '../../features/auth/domain/repositories/auth_repository.dart';
import '../../data/repositories/auth_repository.dart' as api;
import '../../logic/cubits/auth_cubit.dart';
import '../../features/accounts/domain/repositories/account_repository.dart';
import '../../features/accounts/data/repositories/account_repository.dart';
import '../../logic/cubits/account_cubit.dart';
import '../../features/items/domain/repositories/item_repository.dart';
import '../../features/items/data/repositories/item_repository.dart';
import '../../logic/cubits/item_cubit.dart';
import '../../features/contacts/domain/repositories/contact_repository.dart';
import '../../features/contacts/data/repositories/contact_repository_impl.dart';
import '../../logic/cubits/contact_cubit.dart';
import '../../features/documents/domain/repositories/document_repository.dart';
import '../../features/documents/data/repositories/document_repository_impl.dart';
import '../../logic/cubits/document_cubit.dart';
import '../../logic/cubits/document_transaction_cubit.dart';
import '../../features/reconciliations/domain/repositories/reconciliation_repository.dart';
import '../../features/reconciliations/data/repositories/reconciliation_repository.dart';
import '../../logic/cubits/reconciliation_cubit.dart';
import '../../domain/repositories/transfer_repository.dart';
import '../../domain/repositories/transaction_repository.dart';
import '../../features/companies/domain/repositories/company_repository.dart';
import '../../features/companies/data/repositories/company_repository_impl.dart';
import '../../features/companies/presentation/cubit/company_cubit.dart';
import '../../features/profile/domain/repositories/profile_repository.dart';
import '../../features/profile/data/repositories/profile_repository_impl.dart';
import '../../features/profile/presentation/cubit/profile_cubit.dart';
import '../../features/dashboard/domain/repositories/dashboard_repository.dart';
import '../../features/dashboard/data/repositories/dashboard_repository.dart';
import '../../logic/cubits/dashboard_cubit.dart';
import '../../features/transfers/presentation/cubit/transfer_cubit.dart';
import '../../features/transactions/presentation/cubit/transaction_cubit.dart';
import '../../features/reports/domain/repositories/report_repository.dart';
import '../../features/reports/presentation/cubit/report_cubit.dart';
import '../../features/categories/domain/repositories/category_repository.dart';
import '../../features/categories/presentation/cubit/category_cubit.dart';
import '../../features/currencies/domain/repositories/currency_repository.dart';
import '../../features/currencies/presentation/cubit/currency_cubit.dart';
import '../../features/taxes/domain/repositories/tax_repository.dart';
import '../../features/taxes/presentation/cubit/tax_cubit.dart';
import '../../features/settings/domain/repositories/setting_repository.dart';
import '../../features/settings/presentation/cubit/setting_cubit.dart';
import '../../features/translations/domain/repositories/translation_repository.dart';
import '../../features/translations/presentation/cubit/translation_cubit.dart';
import '../../features/users/domain/repositories/user_repository.dart';
import '../../features/users/data/repositories/user_repository_impl.dart';
import '../../features/users/presentation/cubit/user_cubit.dart';
import '../../features/users/presentation/cubit/user_action_cubit.dart';
import '../network/api_client.dart';
import '../network/auth_interceptor.dart';

final sl = GetIt.instance;

Future<void> init() async {
